--------------------------------------------------------
--  颇老捞 积己凳 - 拳夸老-10岿-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORACLE_MEMBER
--------------------------------------------------------

  CREATE TABLE "DEV37ID"."ORACLE_MEMBER" 
   (	"ORA_ID" VARCHAR2(10 BYTE), 
	"ORA_PW" VARCHAR2(10 BYTE), 
	"ORA_LEVEL" VARCHAR2(10 BYTE), 
	"ORA_NAME" VARCHAR2(20 BYTE), 
	"ORA_EMAIL" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEV37ID.ORACLE_MEMBER
SET DEFINE OFF;
Insert into DEV37ID.ORACLE_MEMBER (ORA_ID,ORA_PW,ORA_LEVEL,ORA_NAME,ORA_EMAIL) values ('id001','pw001','包府磊','全01','001@ksmart.or.kr');
Insert into DEV37ID.ORACLE_MEMBER (ORA_ID,ORA_PW,ORA_LEVEL,ORA_NAME,ORA_EMAIL) values ('id002','pw002','魄概磊','全02','002@ksmart.or.kr');
Insert into DEV37ID.ORACLE_MEMBER (ORA_ID,ORA_PW,ORA_LEVEL,ORA_NAME,ORA_EMAIL) values ('id003','pw003','备概磊','全03','003@ksmart.or.kr');
Insert into DEV37ID.ORACLE_MEMBER (ORA_ID,ORA_PW,ORA_LEVEL,ORA_NAME,ORA_EMAIL) values ('id004','pw004','备概磊','全04','004@ksmart.or.kr');
Insert into DEV37ID.ORACLE_MEMBER (ORA_ID,ORA_PW,ORA_LEVEL,ORA_NAME,ORA_EMAIL) values ('id005','pw005','备概磊','全05','005@ksmart.or.kr');
--------------------------------------------------------
--  DDL for Index SYS_C007002
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEV37ID"."SYS_C007002" ON "DEV37ID"."ORACLE_MEMBER" ("ORA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORACLE_MEMBER
--------------------------------------------------------

  ALTER TABLE "DEV37ID"."ORACLE_MEMBER" ADD PRIMARY KEY ("ORA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEV37ID"."ORACLE_MEMBER" MODIFY ("ORA_NAME" NOT NULL ENABLE);
  ALTER TABLE "DEV37ID"."ORACLE_MEMBER" MODIFY ("ORA_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "DEV37ID"."ORACLE_MEMBER" MODIFY ("ORA_PW" NOT NULL ENABLE);
  ALTER TABLE "DEV37ID"."ORACLE_MEMBER" MODIFY ("ORA_ID" NOT NULL ENABLE);
