--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KSMART_BOARD
--------------------------------------------------------

  CREATE TABLE "DEV37ID"."KSMART_BOARD" 
   (	"BOARD_NUM" NUMBER, 
	"BOARD_NAME" VARCHAR2(20 BYTE), 
	"BOARD_PASS" VARCHAR2(15 BYTE), 
	"BOARD_SUBJECT" VARCHAR2(50 BYTE), 
	"BOARD_CONTENT" VARCHAR2(2000 BYTE), 
	"BOARD_FILE" VARCHAR2(50 BYTE), 
	"BOARD_RE_REF" NUMBER, 
	"BOARD_RE_LEV" NUMBER, 
	"BOARD_RE_SEQ" NUMBER, 
	"BOARD_READCOUNT" NUMBER, 
	"BOARD_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEV37ID.KSMART_BOARD
SET DEFINE OFF;
Insert into DEV37ID.KSMART_BOARD (BOARD_NUM,BOARD_NAME,BOARD_PASS,BOARD_SUBJECT,BOARD_CONTENT,BOARD_FILE,BOARD_RE_REF,BOARD_RE_LEV,BOARD_RE_SEQ,BOARD_READCOUNT,BOARD_DATE) values (1,'글쓴이1','1','제목1','내용1','upload_file.txt',1,0,0,2,to_date('20/10/26','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C006997
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEV37ID"."SYS_C006997" ON "DEV37ID"."KSMART_BOARD" ("BOARD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table KSMART_BOARD
--------------------------------------------------------

  ALTER TABLE "DEV37ID"."KSMART_BOARD" ADD PRIMARY KEY ("BOARD_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
